### PR TITLE
prefer ActiveSupport.on_load(:action_controller)

### PR DESCRIPTION
**Pull request by patleb**
trim a little bit the load time

### CODE REVIEW

**Comment by patleb** [comment]
unstable ci: Failure/Error: require "solidus_support/extension/feature_helper"

**Comment by tvdeyen** [comment]
Not unstable. `factory_girl` needs to be pinned to 4.8.1

**Comment by patleb** [comment]
my bad, I've corrected the dependency

**Comment by patleb** [comment]
I've reverted the commit, the problem wasn't only changing the dependency where I changed it. Also, I don't think this pull request it worth the time I would take make it work. So, from my point of view, if it's working for the test suite with Ruby 2.5+, then it's working as expected.

**Pull request closed without merging**
