### PR TITLE
Moved the encryptor setting for the User model into the devise config

### PR DESCRIPTION
**Pull request by lukepfarrar**
allowing it to be easily overridden from the local devise config.

### CODE REVIEW

**Comment by gmacdougall** [comment]
@jhawthorn This looks good to me. Can you think of any reasons this might cause problems?

**Comment by Senjai** [comment]
:+1:

**Comment by jhawthorn** [comment]
Only issue I could see is if a store had two devise models side-by-side. I think the benefit of this will reach more users than that edge case.

Sorry for the delay @lukepfarrar. This is great :+1:

**Comment by lukepfarrar** [comment]
Cheers Chaps :-)

**Pull request merged**
