### PR TITLE
Fix locale inconsistence and remove redundant template

### PR DESCRIPTION
**Pull request by bitberry-dev**
Hello guys,

I was removing a devise from one of my projects and came across a few of my notes.

1. When the language is changed on the backend, devise's backend controllers do not react to this, because `set_user_language_locale_key` is not set `:admin_locale`
2. The template `spree/layouts/admin/login_nav` is not used anywhere https://github.com/solidusio/solidus_auth_devise/commit/80bd9f993e83a619407985379878406d8222a1b1#r79287230

This PR fixes this

### CODE REVIEW

**Comment by gsmendoza** [comment]
Thank you @bitberry-dev! I'll investigate the issue with the backend language. For the meantime, can you split the commit into two? Please check out [this article](https://www.aleksandrhovhannisyan.com/blog/atomic-git-commits/) on the benefits of making commits atomic.

Please also check [this article](https://cbea.ms/git-commit/) on ways to improve your git commit messages.

**Comment by gsmendoza** [comment]
Hi @bitberry-dev ! It seems I'm able to reproduce the issue you're having, but I'm not able to confirm if the solution you provided fixes it.

Please let me know if I'm correctly reproducing the issue.

## Expected behavior

Given I have set up and am running the test Rails app like this:

```
git clone git@github.com:gsmendoza/solidus-auth-devise-224.git
cd solidus-auth-devise-224
bundle install
rake db:create
rake db:migrate
rake db:seed
rails s
```

When I visit http://localhost:3000/admin

Then I should see that I am redirected to http://localhost:3000/en/admin/login

And I should see that the Admin locale selector is set to English

When I change the locale in the Admin locale selector to Espanol

Then I should see that the login page's locale is switched to Espanol

## Actual behavior

I remain in http://localhost:3000/en/admin/login. Furthermore, when I refresh the login page, the
Admin locale selector is reset to English (US).

## Result of fix

The [Rails app](https://github.com/gsmendoza/solidus-auth-devise-224) already points to [the proposed fix](https://github.com/gsmendoza/solidus-auth-devise-224/commit/94e652db3c4b8cacfb61dfd2ce83ad71f83259b2) but it doesn't seem to have any effect on the issue.

## Test app setup

Note that the test app is running on Rails 6. I updated the Solidus I18n gems to match this Rails version. The Solidus I18n readme [installation steps](https://github.com/solidusio/solidus_i18n#installation) haven't been updated yet for Rails 6.

**Comment by bitberry-dev** [comment]
Hi :)

1. I split commit into two, no problem 👍

2. Let's see how is the locale determined in solidus

```
def set_user_language
      available_locales = Spree.i18n_available_locales
      locale = [
        params[:locale],
        session[set_user_language_locale_key],
        (config_locale if respond_to?(:config_locale, true)),
        I18n.default_locale
      ].detect do |candidate|
        candidate &&
          available_locales.include?(candidate.to_sym)
      end
      session[set_user_language_locale_key] = locale
      I18n.locale = locale
      Carmen.i18n_backend.locale = locale
end
```

If the locale is not in the params then it extracts from the session. And `set_user_language_locale_key` affects part with session.

In your version, judging by the URL that includes `en`, the locale is most likely defined in the params and it obviously should work :) Because params have the highest priority.

Here video of the bug I'm talking about:

Before patch
https://user-images.githubusercontent.com/3278464/180974474-7e20d206-e05e-4b1a-92e9-9546c2f40e15.mov

After patch
https://user-images.githubusercontent.com/3278464/180974552-58deacea-96a4-4637-9b89-de32d8e273c4.mov

**Comment by bitberry-dev** [comment]
In addition to the previous answer*

To reproduce this in your test app, you need to set for example
`config.i18n.available_locales = [:en, :it]`

And because of the implementation of `Spree.i18n_available_locales` you need to add translation of key `spree.i18n.this_file_language` on additional language, for `:it` it would be `it.spree.i18n.this_file_language` (or just add solidus_i18n gem)

After that you will have a choice of language at the admin bottom left

**Comment by gsmendoza** [comment]
@bitberry-dev I appreciate if you can watch this video testing this PR:

https://user-images.githubusercontent.com/61476/181145574-bb9dcf5c-2478-4b6c-b7f0-6402e649502b.mp4

As I mentioned in the video, I'm not able to confirm that this PR fixes the language selector in the admin login page.

There are two ways we can move forward with this PR. You can either

1. Update the [Rails app](https://github.com/gsmendoza/solidus-auth-devise-224/commits/main) I made to get this PR to work on it, or
2. Create your own Rails app demonstrating that the PR works.

Sorry for the inconvenience. I'm looking forward to getting your PR merged! :)

**Comment by bitberry-dev** [comment]
@gsmendoza Yes you are right. Indeed, there is such a bug - an unauthorized user cannot change the locale in the admin. And I also had this bug in my notes! And I missed that in my video this patch was applied, sorry for that :( Here is it :)

```
# frozen_string_literal: true

module Spree
  module Admin
    module LocaleControllerOverrideGlobalization
      extend Spree::Extension

      overrode do
        # todo send pull request to solidus - unauthorized user can't change language
        skip_before_action :authorize_admin, only: [:set]
      end

      def set
        locale = params[:switch_to_locale].to_s.presence

        if locale && I18n.available_locales.include?(locale.to_sym)
          I18n.locale = locale
          session[set_user_language_locale_key] = locale

          respond_to do |format|
            # overrode only for staying on same page when locale changed todo it is not durable code
            format.json { render json: {locale: locale, location: (request.referrer || admin_url)} }
          end
        else
          respond_to do |format|
            format.json { render json: {locale: I18n.locale}, status: 404 }
          end
        end
      end

      override!
    end
  end
end
```

It just skips `authorize_admin` before `admin/locale#set`

I was thinking how to check this particular bug (locale inconsistency) - in theory it would be possible to change the locale when user logged in and after log out and then check in what locale the login page is, but devise apparently clears the session and locale resets to default :)

Then I can add another commit to the PR, which fixes the problem with setting the locale, and as a result, this PR will fix 3 bugs :)

**Comment by bitberry-dev** [comment]
So, in the end, I sent a PR to your repository with a patch for `admin/locale#set` so that you make sure that my PR fixes locale inconsistence :)

I also recorded two videos with the current solidus auth device and with my fork.

With original solidus_auth_devise:

https://user-images.githubusercontent.com/3278464/181239003-36d2b272-52b8-48e8-8528-6a7f52013bde.mov

With my solidus_auth_devise

https://user-images.githubusercontent.com/3278464/181239130-619ebd16-1198-4019-9233-98e59134dd38.mov

I also found a bug with select2 locale and no fallback there, but that's another story)

**Comment by gsmendoza** [comment]
Thank you @bitberry-dev !

* I've rebased https://github.com/gsmendoza/solidus-auth-devise-224/commits/main with your PR and have confirmed this fix there :+1: 
* I'll submit a PR to Solidus skipping `authorize_admin` before `LocaleController#set`.
* I'm approving this PR, but can I make a minor request? Can you [capitalize the subject line](https://cbea.ms/git-commit/#capitalize) of each commit message? This will make your commit message consistent with the git log of this repo :) 
* I'll request someone else to do a second review of your PR.

**Review by gsmendoza — APPROVED** [review]

**Comment by bitberry-dev** [comment]
@gsmendoza commit messages now capitalized 😉

**Comment by waiting-for-dev** [comment]
> I'll submit a PR to Solidus skipping authorize_admin before LocaleController#set.

Not that dangerous, but it'd mean an unauthorized user can change the admin's locale. That's not ideal. Would it be possible to confirm the change in locale only if the login goes through and revert/not apply if not?

**Comment by gsmendoza** [comment]
@waiting-for-dev 

> Would it be possible to confirm the change in locale only if the login goes through and revert/not apply if not?

* The change in locale automatically takes effect _on_ the login page; it's not something that takes effect only after the actual login. Please see the [with_fix.mov video](https://user-images.githubusercontent.com/3278464/181239130-619ebd16-1198-4019-9233-98e59134dd38.mov) in this PR.

* From a user experience perspective, I think it can be annoying if the locale you have selected in the login page gets reverted immediately after you log in. I think most people would even think that it's a bug that the locale wasn't retained. From their point of view, they were the same person before and after the login. 

* To make the implementation more secure, I think that instead of skipping `authorize_admin` for `LocaleController#set`, we can probably tell `LocaleController#set` where the request came from. If the request came from a guest area of the admin site (e.g. the login page), then we can allow the guest user to call `LocaleController#set`. 

Let me know what you think!

**Comment by waiting-for-dev** [comment]
> From a user experience perspective, I think it can be annoying if the locale you have selected in the login page gets reverted immediately after you log in.

My idea was to preserve it if the login is successful, only rolling back when not. But that's probably not going to play well with the current implementation.

> If the request came from a guest area of the admin site (e.g. the login page), then we can allow the guest user to call LocaleController#set.

And if it didn't come from a guest area, then the user was allowed to change it :slightly_smiling_face: 

I'm ok with skipping authorization for now, as otherwise, I think it'll be very complex. In the end, physical access to the computer is out of this kind of security scope.

**Comment by gsmendoza** [comment]
> My idea was to preserve it if the login is successful, only rolling back when not. 

Sorry, I'm not following this. Let's discuss it offline :)

> And if it didn't come from a guest area, then the user was allowed to change it slightly_smiling_face

Yeah, in hindsight, it's a convoluted implementation that does the same thing as skipping admin authorization :D

@waiting-for-dev Other than that, do you have any other concerns about this PR? Skipping `authorize_admin` before `LocaleController#set` is outside the scope of this PR: it has be done on the Solidus repo.

**Comment by waiting-for-dev** [comment]
I'm worried that if we change `set_user_language_locale_key` [upstream](https://github.com/solidusio/solidus/blob/a22723079f88387f53f72b503db875b9d97aa3f5/backend/app/controllers/spree/admin/base_controller.rb#L15) in `solidus_backend`, that will break the behavior here.

What do you think about extracting the upstream method to a standalone module and including it from `Spree::Admin::BaseController` and the two descendants of the Devise controllers here?

About removing the template, I'd like to check with @kennyadsl that we're not missing anything, but I think it's ok.

**Comment by kennyadsl** [comment]
I have not been yet able to review everything, but I think it's ok to remove that partial now.

**Comment by gsmendoza** [comment]
@waiting-for-dev Something like this?

```ruby
module Spree
  module Admin
    module SetsUserLanguageLocaleKey
      def set_user_language_locale_key
        :admin_locale
      end
    end
  end
end

module Spree
  module Admin
    class BaseController < Spree::BaseController
      # ...

      private

      # Overrides ControllerHelpers::Common
      # We want the admin's locale selection to be different than that on the frontend
      include SetsUserLanguageLocaleKey
    end
  end
end

class Spree::Admin::UserPasswordsController < Devise::PasswordsController
  # ...

  private

  include SetsUserLanguageLocaleKey
end

class Spree::Admin::UserSessionsController < Devise::SessionsController
  # ...

  private

  include SetsUserLanguageLocaleKey
end
```

**Comment by waiting-for-dev** [comment]
> @waiting-for-dev Something like this?

Yes, @gsmendoza, I meant that :slightly_smiling_face: WDYT?

**Comment by gsmendoza** [comment]
It looks good @waiting-for-dev . 

So, to recap, here are our TODOs:

1. Extract SetsUserLanguageLocaleKey module from `Spree::Admin::BaseController`.
2. Skip admin authorization for `Spree::Admin::LocaleController#set`.
3. Include `SetsUserLanguageLocaleKey` in SolidusAuthDevise controllers.

@bitberry-dev I'll add these to our TODO list, but if you want to work on them, let us know!

**Comment by bitberry-dev** [comment]
> @bitberry-dev I'll add these to our TODO list, but if you want to work on them, let us know!

Okay, thanks!

**Comment by gsmendoza** [comment]
Hi @bitberry-dev ! We have just merged https://github.com/solidusio/solidus/pull/4493. We have to wait until Solidus 3.2 is released before we can include `Spree::Admin::SetsUserLanguageLocaleKey` in the Devise controllers of SolidusAuthDevise. For the meantime, I understand that you're able to work around this issue on your app by overriding the controllers. Is that right?

**Comment by bitberry-dev** [comment]
> Hi @bitberry-dev ! We have just merged [solidusio/solidus#4493](https://github.com/solidusio/solidus/pull/4493). We have to wait until Solidus 3.2 is released before we can include `Spree::Admin::SetsUserLanguageLocaleKey` in the Devise controllers of SolidusAuthDevise.

Great news 👍 Thank you

>  For the meantime, I understand that you're able to work around this issue on your app by overriding the controllers. Is that right?

Yes, that's right, I got around this problem for several years with my overrides.

**Comment by gsmendoza** [comment]
> Yes, that's right, I got around this problem for several years with my overrides.

Hehe.. Yeah, let's hope we can get this PR merged soon :)

**Comment by gsmendoza** [comment]
@bitberry-dev Just to let you know that Solidus 3.2 has been released :) Can you update this PR to include `Spree::Admin::SetsUserLanguageLocaleKey` in the Devise controllers? Thank you!

**Comment by bitberry-dev** [comment]
@gsmendoza PR updated, solidus_auth_devise supports solidus since version 2.6, so I check before include if this concern `Spree::Admin::SetsUserLanguageLocaleKey` is defined. When solidus_version in gemspec will bump to 3.2 then this code will need to be fixed.

**Comment by gsmendoza** [comment]
@bitberry-dev The code looks good. However, can you rebase your branch against master? That might be needed in order to get CI to pass. Thanks!

**Comment by bitberry-dev** [comment]
@gsmendoza Now all checks passed

**Review by waiting-for-dev — APPROVED** [review]

**Review by kennyadsl — COMMENTED** [review]
Hello @bitberry-dev! Thanks for the PR and for the back and forth in addressing it. I think that in the end, it has been worth the effort since this seems the cleaner solution.

I have a last request though. If I got it correctly, when we stop supporting Solidus 3.1, we can remove the `if` and just leave the `include`. Can we add some reference to that for future developers? I think it's acceptable both as code comment, additional paragraph in the commit description or a note in the PR description, up to you! 

Thanks again to you and everyone else involved in this change!

**Comment by bitberry-dev** [comment]
@kennyadsl Sure, added comments in the code and in commit description

**Review by kennyadsl — APPROVED** [review]

**Comment by kennyadsl** [comment]
Thanks @bitberry-dev!!!

**Comment by bitberry-dev** [comment]
@kennyadsl You are welcome :)

**Pull request merged**
