### PR TITLE
Remove some redundant includes

### PR DESCRIPTION
**Pull request by jordan-brough**
UserMethods was added in 953d1ddffec1e7b7d3290e10c8abbf9f02c98a2c and
it already includes these two modules.

This happens to make it easier for us to do some address refactoring
as well.

### CODE REVIEW

**Comment by Senjai** [comment]
:+1:

**Comment by gvaughn** [comment]
:thumbsup:

**Comment by magnusvk** [comment]
:+1:

**Comment by gmacdougall** [comment]
:+1:

**Pull request merged**
