### PR TITLE
Introduce Rubocop for linting

### PR DESCRIPTION
**Pull request by aitbw**
In an effort to improve tooling and to achieve a more consistent development environment, this PR aims to include Rubocop to this gem, as well as fix all the offenses based on the [Rubocop config file](https://github.com/solidusio/solidus/blob/master/.rubocop.yml) that Solidus uses.

**TO-DO**:

* [x] Fix `Lint/Syntax: unexpected token error` raised by [this line](https://github.com/solidusio/solidus_auth_devise/blob/master/lib/controllers/frontend/spree/users_controller.rb#L48)

### CODE REVIEW

**Comment by aitbw** [comment]
There's one error present in Travis (locally too!) for Solidus v2.5 —apparently, something is interfering with Bundler when it tries to resolve the dependencies.

**Comment by tvdeyen** [comment]
@aitbw builds should work know. Would you mind to rebase as this is great work I would like to merge?

**Comment by aitbw** [comment]
Done @tvdeyen :ok_hand:

**Comment by tvdeyen** [comment]
Thanks

**Pull request merged**
