### PR TITLE
Remove brittle spec

### PR DESCRIPTION
**Pull request by adammathys**
Provides no real value, since it stubs out the thing it was supposed to test.

### CODE REVIEW

**Comment by jordan-brough** [comment]
haha funny. :+1: 

while we're in here are we also able to remove [this](https://github.com/solidusio/solidus_auth_devise/blob/fe372f3c1ad75e00c0246e6b5ae755cdaae9d4cd/spec/support/spree.rb#L7) now?

**Comment by adammathys** [comment]
Quite possibly, I'll remove it and see what happens.

**Comment by BenMorganIO** [comment]
:+1:

**Comment by magnusvk** [comment]
:+1:

**Comment by gmacdougall** [comment]
:+1:

**Pull request merged**
