### PR TITLE
Admin navigation sidebar

### PR DESCRIPTION
**Pull request by Sinetheta**
Changes to accompany https://github.com/solidusio/solidus/pull/509

screen shot 2015-11-20 at 11 22 47 am

### CODE REVIEW

**Comment by Senjai** [comment]
Seems reasonable :+1:, save failures.

**Comment by Sinetheta** [comment]
Ya, it's a chicken/egg. I need the Solidus change to land before the specs can run here.

**Comment by Senjai** [comment]
:shipit:

**Comment by jhawthorn** [comment]
@Sinetheta we probably want to bump the solidus dependency to `1.2.0.alpha` here

**Comment by Sinetheta** [comment]
Yup up, then we can get it back to happy.

**Comment by athal7** [comment]
:+1:

**Comment by jhawthorn** [comment]
Thanks all

**Pull request merged**
