### PR TITLE
Fix spelling of locale logged_in_successfully

### PR DESCRIPTION
**Pull request by nspinazz89**
This addresses solidusio/solidus#3346 and ensures existing projects will not break by providing a default.

### CODE REVIEW

**Comment by nspinazz89** [comment]
Thanks for the feedback @kennyadsl, alternatively we could just add it as an extra option in the yaml file. I'm good with either though!

**Comment by kennyadsl** [comment]
@jacobherrington I agree this could be documented better. The commit message should explain why we are doing this change and we should probably also link https://github.com/solidusio/solidus/pull/3346 in the PR description.

**Comment by kennyadsl** [comment]
I'm a bit hesitant merging this since I'd prefer to see that comment text in the commit description instead.

**Comment by spaghetticode** [comment]
@nspinazz89 can you improve a bit the commit message, so it's more clear why we're doing this? After that, I think this is good to merge!

**Comment by nspinazz89** [comment]
@kennyadsl and @spaghetticode is this sufficient or are there some other changes I should make as well?

**Comment by kennyadsl** [comment]
I still think we should remove code comments if we moved in the commit description. Thanks!

**Pull request closed without merging**
